In [19]:
import numpy as np
from numpy import linalg as LA

In [65]:
X1 = np.diag([1, 2, 3, 4, 5])
X2 = np.diag([2, 10])
Rn = X1.shape[1]
obs = X1.shape[0]
initial = np.random.choice(obs, 3, replace = False)
print(X1)
print(X2)
print(initial)
initial = X1[initial, ]
print(initial)
for i in initial:
    print(X1 - i)
    print(LA.norm(X1 - i, axis = 1))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[ 2  0]
 [ 0 10]]
[4 2 1]
[[0 0 0 0 5]
 [0 0 3 0 0]
 [0 2 0 0 0]]
[[ 1  0  0  0 -5]
 [ 0  2  0  0 -5]
 [ 0  0  3  0 -5]
 [ 0  0  0  4 -5]
 [ 0  0  0  0  0]]
[5.09901951 5.38516481 5.83095189 6.40312424 0.        ]
[[ 1  0 -3  0  0]
 [ 0  2 -3  0  0]
 [ 0  0  0  0  0]
 [ 0  0 -3  4  0]
 [ 0  0 -3  0  5]]
[3.16227766 3.60555128 0.         5.         5.83095189]
[[ 1 -2  0  0  0]
 [ 0  0  0  0  0]
 [ 0 -2  3  0  0]
 [ 0 -2  0  4  0]
 [ 0 -2  0  0  5]]
[2.23606798 0.         3.60555128 4.47213595 5.38516481]


In [52]:
np.ones(2)
X1 = np.diag([1, 2, 3, 4, 5])
print(X1)
obs = X1.shape[0]
np.full_like(np.ones(obs), 1/obs)
np.random.choice(obs, 3, replace = False)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


array([0, 4, 1])

In [80]:
X = np.zeros((2, 3))
X

array([[0., 0., 0.],
       [0., 0., 0.]])

In [93]:
a = np.arange(9).reshape(3,3)
print(a)
a[:, 0].argmax()

[[0 1 2]
 [3 4 5]
 [6 7 8]]


2

In [ ]:
# Implement the class
class kMeans():
    def __init__(self, n_clusters = 3, max_iter = 100):
        self.n_clusters = n_clusters
        # Other init...
        
    def fit(self, X):
        # Randomly select k (n_clusters) from my X to be my centroids
        obs = X.shape[0]
        centroids = np.random.choice(obs, 3, replace = False)
        centroids = X1[centroids, ]
        distance = np.zeros((self.n_clusters, obs))
        for i in range(max_iter):
            # Update centroids
            # Calculate distances from X to my centroids. (broadcasting)
            for i in range(self.n_clusters):
                dist = LA.norm(X - centroids[i, ], axis = 1)
                distance[i, ] = dist
            
            for i in range(obs):
                labels = distance[:, i].argmax()    
            # Label my data to which centroid it belongs using 

            # Update centroids based on the labels 
            
            
            if np.allclose(new_centroid, self.centroids):
                break
        
        pass
        
    def predict(self, test_data):
        pass
    # YOUR CODE HERE

In [ ]:
# test the class
def test_kmeans():
    # Test 1: Basic clustering with clearly separated points
    X = np.array([
        [0, 0], [1, 0], [0, 1],      # Cluster 1
        [5, 5], [6, 5], [5, 6],      # Cluster 2
        [10, 10], [11, 10], [10, 11]  # Cluster 3
    ])
    
    np.random.seed(42)
    kmeans = KMeans(n_clusters=3)
    kmeans.fit(X)
    
    # Test number of centroids
    assert len(kmeans.centroids) == 3, "Should have 3 centroids"
    
    # Test centroid shapes
    assert kmeans.centroids.shape == (3, 2), "Centroids should be 2D"

    X_test = np.random.normal(4, 1, (10, 2))
    
    # Predict clusters for test data
    predictions = kmeans.predict(X_test)
    print("Predictions for test data:", predictions)
    
    # Test 2: Random data
    np.random.seed(42)
    X_random = np.random.randn(100, 2) * 3
    X_random[:33] += np.array([10, 10])
    X_random[33:66] += np.array([-10, -10])
    
    kmeans = KMeans(n_clusters=3)
    kmeans.fit(X_random)
    
    distances = np.linalg.norm(X_random[:, np.newaxis] - kmeans.centroids, axis=2)
    labels = np.argmin(distances, axis=1)
    
    # Test cluster sizes are reasonable
    unique, counts = np.unique(labels, return_counts=True)
    assert len(unique) == 3, "Should have 3 unique clusters"
    assert all(counts > 5), "Each cluster should have multiple points"
    
    print("All tests passed!")
    

if __name__ == "__main__":
    test_kmeans()